// Seed catalog (spec §12). videoUrl points to a stable public how-to clip the
// app links to (it does not host video). Expand freely — ids are slugged from
// name at seed time. Keep names as common gym names so the plan-generation LLM's
// output matches by name.

export interface SeedExercise {
  name: string;
  primaryMuscle: string;
  secondaryMuscles: string[];
  equipment: string;
  instructions: string;
  formCues: string[];
  videoUrl: string;
  difficulty: 'beginner' | 'intermediate' | 'advanced';
}

export const EXERCISES: SeedExercise[] = [
  {
    name: 'Barbell Back Squat',
    primaryMuscle: 'Quadriceps',
    secondaryMuscles: ['Glutes', 'Hamstrings', 'Core'],
    equipment: 'Barbell',
    instructions:
      'Bar on upper traps, brace, descend until hips below knees, drive up through mid-foot.',
    formCues: ['Brace before you unrack', 'Knees track over toes', 'Neutral spine'],
    videoUrl: 'https://www.youtube.com/watch?v=ultWZbUMPL8',
    difficulty: 'intermediate',
  },
  {
    name: 'Conventional Deadlift',
    primaryMuscle: 'Hamstrings',
    secondaryMuscles: ['Glutes', 'Erectors', 'Lats'],
    equipment: 'Barbell',
    instructions: 'Hinge to grip bar, flat back, push the floor away, lock out hips.',
    formCues: ['Bar over mid-foot', 'Lats tight', 'Hips and chest rise together'],
    videoUrl: 'https://www.youtube.com/watch?v=op9kVnSso6Q',
    difficulty: 'intermediate',
  },
  {
    name: 'Bench Press',
    primaryMuscle: 'Chest',
    secondaryMuscles: ['Triceps', 'Front Delts'],
    equipment: 'Barbell',
    instructions: 'Retract scapula, lower to lower chest, press up and slightly back.',
    formCues: ['Feet planted', 'Elbows ~75°', 'Touch and control'],
    videoUrl: 'https://www.youtube.com/watch?v=rT7DgCr-3pg',
    difficulty: 'beginner',
  },
  {
    name: 'Overhead Press',
    primaryMuscle: 'Shoulders',
    secondaryMuscles: ['Triceps', 'Upper Chest', 'Core'],
    equipment: 'Barbell',
    instructions: 'Press bar overhead from front-rack, move head back then through.',
    formCues: ['Squeeze glutes', 'Bar over mid-foot at lockout', "Don't lean back"],
    videoUrl: 'https://www.youtube.com/watch?v=2yjwXTZQDDI',
    difficulty: 'intermediate',
  },
  {
    name: 'Pull-Up',
    primaryMuscle: 'Lats',
    secondaryMuscles: ['Biceps', 'Upper Back'],
    equipment: 'Bodyweight',
    instructions: 'Hang from bar, pull chest to bar, control the descent.',
    formCues: ['Depress scapula first', 'Drive elbows down', 'Full range'],
    videoUrl: 'https://www.youtube.com/watch?v=eGo4IYlbE5g',
    difficulty: 'intermediate',
  },
  {
    name: 'Barbell Row',
    primaryMuscle: 'Upper Back',
    secondaryMuscles: ['Lats', 'Biceps', 'Erectors'],
    equipment: 'Barbell',
    instructions: 'Hinge ~45°, row bar to lower ribs, squeeze, lower under control.',
    formCues: ['Flat back', 'Pull to navel', 'No torso bounce'],
    videoUrl: 'https://www.youtube.com/watch?v=9efgcAjQe7E',
    difficulty: 'intermediate',
  },
  {
    name: 'Romanian Deadlift',
    primaryMuscle: 'Hamstrings',
    secondaryMuscles: ['Glutes', 'Erectors'],
    equipment: 'Barbell',
    instructions: 'Soft knees, push hips back, lower bar along legs to mid-shin, drive hips forward.',
    formCues: ['Bar stays close', 'Feel hamstring stretch', 'Neutral spine'],
    videoUrl: 'https://www.youtube.com/watch?v=JCXUYuzwNrM',
    difficulty: 'beginner',
  },
  {
    name: 'Hip Thrust',
    primaryMuscle: 'Glutes',
    secondaryMuscles: ['Hamstrings'],
    equipment: 'Barbell',
    instructions: 'Upper back on bench, bar over hips, drive hips to full extension.',
    formCues: ['Chin tucked', 'Squeeze glutes at top', 'Ribs down'],
    videoUrl: 'https://www.youtube.com/watch?v=LM8XHLYJoYs',
    difficulty: 'beginner',
  },
  {
    name: 'Dumbbell Incline Press',
    primaryMuscle: 'Upper Chest',
    secondaryMuscles: ['Front Delts', 'Triceps'],
    equipment: 'Dumbbell',
    instructions: 'Bench at ~30°, press dumbbells up and slightly together.',
    formCues: ['Control the stretch', 'Wrists stacked', "Don't clang at top"],
    videoUrl: 'https://www.youtube.com/watch?v=8iPEnn-ltC8',
    difficulty: 'beginner',
  },
  {
    name: 'Lat Pulldown',
    primaryMuscle: 'Lats',
    secondaryMuscles: ['Biceps', 'Upper Back'],
    equipment: 'Cable',
    instructions: 'Pull bar to upper chest, drive elbows down, control back up.',
    formCues: ['Slight lean back', 'Lead with elbows', 'Full stretch at top'],
    videoUrl: 'https://www.youtube.com/watch?v=CAwf7n6Luuc',
    difficulty: 'beginner',
  },
  {
    name: 'Seated Cable Row',
    primaryMuscle: 'Upper Back',
    secondaryMuscles: ['Lats', 'Biceps'],
    equipment: 'Cable',
    instructions: 'Pull handle to torso, squeeze shoulder blades, extend under control.',
    formCues: ['Tall chest', "Don't shrug", 'Pause at contraction'],
    videoUrl: 'https://www.youtube.com/watch?v=GZbfZ033f74',
    difficulty: 'beginner',
  },
  {
    name: 'Face Pull',
    primaryMuscle: 'Rear Delts',
    secondaryMuscles: ['Upper Back', 'Rotator Cuff'],
    equipment: 'Cable',
    instructions: 'Pull rope to face, externally rotate, squeeze rear delts. Great for posture.',
    formCues: ['High elbows', 'Thumbs back', 'Slow eccentric'],
    videoUrl: 'https://www.youtube.com/watch?v=rep-qVOkqgk',
    difficulty: 'beginner',
  },
  {
    name: 'Plank',
    primaryMuscle: 'Core',
    secondaryMuscles: ['Shoulders', 'Glutes'],
    equipment: 'Bodyweight',
    instructions: 'Forearms down, body in a straight line, brace and hold.',
    formCues: ['Ribs down', 'Squeeze glutes', "Don't sag hips"],
    videoUrl: 'https://www.youtube.com/watch?v=ASdvN_XEl_c',
    difficulty: 'beginner',
  },
  {
    name: 'Dead Bug',
    primaryMuscle: 'Core',
    secondaryMuscles: ['Hip Flexors'],
    equipment: 'Bodyweight',
    instructions: 'On back, extend opposite arm/leg while keeping low back flat. Deep-core work.',
    formCues: ['Low back pinned', 'Exhale on extension', 'Move slowly'],
    videoUrl: 'https://www.youtube.com/watch?v=4XLEnwUr1d8',
    difficulty: 'beginner',
  },
  {
    name: 'Walking Lunge',
    primaryMuscle: 'Quadriceps',
    secondaryMuscles: ['Glutes', 'Hamstrings'],
    equipment: 'Dumbbell',
    instructions: 'Step forward, drop back knee toward floor, drive up and continue.',
    formCues: ['Torso tall', 'Front shin vertical', 'Controlled steps'],
    videoUrl: 'https://www.youtube.com/watch?v=L8fvypPrzzs',
    difficulty: 'beginner',
  },
  {
    name: 'Leg Press',
    primaryMuscle: 'Quadriceps',
    secondaryMuscles: ['Glutes', 'Hamstrings'],
    equipment: 'Machine',
    instructions: 'Feet shoulder-width on platform, lower to ~90°, press without locking hard.',
    formCues: ['Lower back stays down', 'Knees track toes', 'Controlled depth'],
    videoUrl: 'https://www.youtube.com/watch?v=IZxyjW7MPJQ',
    difficulty: 'beginner',
  },
  {
    name: 'Dumbbell Lateral Raise',
    primaryMuscle: 'Side Delts',
    secondaryMuscles: [],
    equipment: 'Dumbbell',
    instructions: 'Raise dumbbells out to shoulder height with a slight bend, lower slowly.',
    formCues: ['Lead with elbows', 'No swinging', 'Pinky slightly up'],
    videoUrl: 'https://www.youtube.com/watch?v=3VcKaXpzqRo',
    difficulty: 'beginner',
  },
  {
    name: 'Barbell Curl',
    primaryMuscle: 'Biceps',
    secondaryMuscles: ['Forearms'],
    equipment: 'Barbell',
    instructions: 'Curl bar with elbows fixed, squeeze, lower under control.',
    formCues: ['Elbows pinned', 'No swing', 'Full extension'],
    videoUrl: 'https://www.youtube.com/watch?v=kwG2ipFRgfo',
    difficulty: 'beginner',
  },
  {
    name: 'Triceps Pushdown',
    primaryMuscle: 'Triceps',
    secondaryMuscles: [],
    equipment: 'Cable',
    instructions: 'Push rope/bar down to lockout, keep elbows tucked, control the return.',
    formCues: ['Elbows at sides', 'Full lockout', 'Slow eccentric'],
    videoUrl: 'https://www.youtube.com/watch?v=2-LAMcpzODU',
    difficulty: 'beginner',
  },
];
