// Seed catalog (spec §12). videoUrl points to a stable public how-to clip the
// app links to (it does not host video). Expand freely — ids are slugged from
// name at seed time. Keep names as common gym names so the plan-generation LLM's
// output matches by name.

export interface SeedExercise {
  name: string;
  primaryMuscle: string;
  secondaryMuscles: string[];
  equipment: string;
  instructions: string;
  formCues: string[];
  videoUrl: string;
  difficulty: 'beginner' | 'intermediate' | 'advanced';
}

export const EXERCISES: SeedExercise[] = [
  {
    name: 'Barbell Back Squat',
    primaryMuscle: 'Quadriceps',
    secondaryMuscles: ['Glutes', 'Hamstrings', 'Core'],
    equipment: 'Barbell',
    instructions:
      'Bar on upper traps, brace, descend until hips below knees, drive up through mid-foot.',
    formCues: ['Brace before you unrack', 'Knees track over toes', 'Neutral spine'],
    videoUrl: 'https://www.youtube.com/watch?v=ultWZbUMPL8',
    difficulty: 'intermediate',
  },
  {
    name: 'Conventional Deadlift',
    primaryMuscle: 'Hamstrings',
    secondaryMuscles: ['Glutes', 'Erectors', 'Lats'],
    equipment: 'Barbell',
    instructions: 'Hinge to grip bar, flat back, push the floor away, lock out hips.',
    formCues: ['Bar over mid-foot', 'Lats tight', 'Hips and chest rise together'],
    videoUrl: 'https://www.youtube.com/watch?v=op9kVnSso6Q',
    difficulty: 'intermediate',
  },
  {
    name: 'Bench Press',
    primaryMuscle: 'Chest',
    secondaryMuscles: ['Triceps', 'Front Delts'],
    equipment: 'Barbell',
    instructions: 'Retract scapula, lower to lower chest, press up and slightly back.',
    formCues: ['Feet planted', 'Elbows ~75°', 'Touch and control'],
    videoUrl: 'https://www.youtube.com/watch?v=rT7DgCr-3pg',
    difficulty: 'beginner',
  },
  {
    name: 'Overhead Press',
    primaryMuscle: 'Shoulders',
    secondaryMuscles: ['Triceps', 'Upper Chest', 'Core'],
    equipment: 'Barbell',
    instructions: 'Press bar overhead from front-rack, move head back then through.',
    formCues: ['Squeeze glutes', 'Bar over mid-foot at lockout', "Don't lean back"],
    videoUrl: 'https://www.youtube.com/watch?v=2yjwXTZQDDI',
    difficulty: 'intermediate',
  },
  {
    name: 'Pull-Up',
    primaryMuscle: 'Lats',
    secondaryMuscles: ['Biceps', 'Upper Back'],
    equipment: 'Bodyweight',
    instructions: 'Hang from bar, pull chest to bar, control the descent.',
    formCues: ['Depress scapula first', 'Drive elbows down', 'Full range'],
    videoUrl: 'https://www.youtube.com/watch?v=eGo4IYlbE5g',
    difficulty: 'intermediate',
  },
  {
    name: 'Barbell Row',
    primaryMuscle: 'Upper Back',
    secondaryMuscles: ['Lats', 'Biceps', 'Erectors'],
    equipment: 'Barbell',
    instructions: 'Hinge ~45°, row bar to lower ribs, squeeze, lower under control.',
    formCues: ['Flat back', 'Pull to navel', 'No torso bounce'],
    videoUrl: 'https://www.youtube.com/watch?v=9efgcAjQe7E',
    difficulty: 'intermediate',
  },
  {
    name: 'Romanian Deadlift',
    primaryMuscle: 'Hamstrings',
    secondaryMuscles: ['Glutes', 'Erectors'],
    equipment: 'Barbell',
    instructions: 'Soft knees, push hips back, lower bar along legs to mid-shin, drive hips forward.',
    formCues: ['Bar stays close', 'Feel hamstring stretch', 'Neutral spine'],
    videoUrl: 'https://www.youtube.com/watch?v=JCXUYuzwNrM',
    difficulty: 'beginner',
  },
  {
    name: 'Hip Thrust',
    primaryMuscle: 'Glutes',
    secondaryMuscles: ['Hamstrings'],
    equipment: 'Barbell',
    instructions: 'Upper back on bench, bar over hips, drive hips to full extension.',
    formCues: ['Chin tucked', 'Squeeze glutes at top', 'Ribs down'],
    videoUrl: 'https://www.youtube.com/watch?v=LM8XHLYJoYs',
    difficulty: 'beginner',
  },
  {
    name: 'Dumbbell Incline Press',
    primaryMuscle: 'Upper Chest',
    secondaryMuscles: ['Front Delts', 'Triceps'],
    equipment: 'Dumbbell',
    instructions: 'Bench at ~30°, press dumbbells up and slightly together.',
    formCues: ['Control the stretch', 'Wrists stacked', "Don't clang at top"],
    videoUrl: 'https://www.youtube.com/watch?v=8iPEnn-ltC8',
    difficulty: 'beginner',
  },
  {
    name: 'Lat Pulldown',
    primaryMuscle: 'Lats',
    secondaryMuscles: ['Biceps', 'Upper Back'],
    equipment: 'Cable',
    instructions: 'Pull bar to upper chest, drive elbows down, control back up.',
    formCues: ['Slight lean back', 'Lead with elbows', 'Full stretch at top'],
    videoUrl: 'https://www.youtube.com/watch?v=CAwf7n6Luuc',
    difficulty: 'beginner',
  },
  {
    name: 'Seated Cable Row',
    primaryMuscle: 'Upper Back',
    secondaryMuscles: ['Lats', 'Biceps'],
    equipment: 'Cable',
    instructions: 'Pull handle to torso, squeeze shoulder blades, extend under control.',
    formCues: ['Tall chest', "Don't shrug", 'Pause at contraction'],
    videoUrl: 'https://www.youtube.com/watch?v=GZbfZ033f74',
    difficulty: 'beginner',
  },
  {
    name: 'Face Pull',
    primaryMuscle: 'Rear Delts',
    secondaryMuscles: ['Upper Back', 'Rotator Cuff'],
    equipment: 'Cable',
    instructions: 'Pull rope to face, externally rotate, squeeze rear delts. Great for posture.',
    formCues: ['High elbows', 'Thumbs back', 'Slow eccentric'],
    videoUrl: 'https://www.youtube.com/watch?v=rep-qVOkqgk',
    difficulty: 'beginner',
  },
  {
    name: 'Plank',
    primaryMuscle: 'Core',
    secondaryMuscles: ['Shoulders', 'Glutes'],
    equipment: 'Bodyweight',
    instructions: 'Forearms down, body in a straight line, brace and hold.',
    formCues: ['Ribs down', 'Squeeze glutes', "Don't sag hips"],
    videoUrl: 'https://www.youtube.com/watch?v=ASdvN_XEl_c',
    difficulty: 'beginner',
  },
  {
    name: 'Dead Bug',
    primaryMuscle: 'Core',
    secondaryMuscles: ['Hip Flexors'],
    equipment: 'Bodyweight',
    instructions: 'On back, extend opposite arm/leg while keeping low back flat. Deep-core work.',
    formCues: ['Low back pinned', 'Exhale on extension', 'Move slowly'],
    videoUrl: 'https://www.youtube.com/watch?v=4XLEnwUr1d8',
    difficulty: 'beginner',
  },
  {
    name: 'Walking Lunge',
    primaryMuscle: 'Quadriceps',
    secondaryMuscles: ['Glutes', 'Hamstrings'],
    equipment: 'Dumbbell',
    instructions: 'Step forward, drop back knee toward floor, drive up and continue.',
    formCues: ['Torso tall', 'Front shin vertical', 'Controlled steps'],
    videoUrl: 'https://www.youtube.com/watch?v=L8fvypPrzzs',
    difficulty: 'beginner',
  },
  {
    name: 'Leg Press',
    primaryMuscle: 'Quadriceps',
    secondaryMuscles: ['Glutes', 'Hamstrings'],
    equipment: 'Machine',
    instructions: 'Feet shoulder-width on platform, lower to ~90°, press without locking hard.',
    formCues: ['Lower back stays down', 'Knees track toes', 'Controlled depth'],
    videoUrl: 'https://www.youtube.com/watch?v=IZxyjW7MPJQ',
    difficulty: 'beginner',
  },
  {
    name: 'Dumbbell Lateral Raise',
    primaryMuscle: 'Side Delts',
    secondaryMuscles: [],
    equipment: 'Dumbbell',
    instructions: 'Raise dumbbells out to shoulder height with a slight bend, lower slowly.',
    formCues: ['Lead with elbows', 'No swinging', 'Pinky slightly up'],
    videoUrl: 'https://www.youtube.com/watch?v=3VcKaXpzqRo',
    difficulty: 'beginner',
  },
  {
    name: 'Barbell Curl',
    primaryMuscle: 'Biceps',
    secondaryMuscles: ['Forearms'],
    equipment: 'Barbell',
    instructions: 'Curl bar with elbows fixed, squeeze, lower under control.',
    formCues: ['Elbows pinned', 'No swing', 'Full extension'],
    videoUrl: 'https://www.youtube.com/watch?v=kwG2ipFRgfo',
    difficulty: 'beginner',
  },
  {
    name: 'Triceps Pushdown',
    primaryMuscle: 'Triceps',
    secondaryMuscles: [],
    equipment: 'Cable',
    instructions: 'Push rope/bar down to lockout, keep elbows tucked, control the return.',
    formCues: ['Elbows at sides', 'Full lockout', 'Slow eccentric'],
    videoUrl: 'https://www.youtube.com/watch?v=2-LAMcpzODU',
    difficulty: 'beginner',
  },
  {
    name: 'Front Squat',
    primaryMuscle: 'Quadriceps',
    secondaryMuscles: ['Glutes', 'Core', 'Upper Back'],
    equipment: 'Barbell',
    instructions: 'Bar in front-rack on delts, elbows high, descend upright, drive up.',
    formCues: ['Elbows up', 'Stay vertical', 'Brace hard'],
    videoUrl: 'https://www.youtube.com/watch?v=uYumuL_G_V0',
    difficulty: 'advanced',
  },
  {
    name: 'Goblet Squat',
    primaryMuscle: 'Quadriceps',
    secondaryMuscles: ['Glutes', 'Core'],
    equipment: 'Dumbbell',
    instructions: 'Hold a dumbbell at chest, squat between the knees, drive up tall.',
    formCues: ['Chest up', 'Knees out', 'Heels down'],
    videoUrl: 'https://www.youtube.com/watch?v=MeIiIdhvXT4',
    difficulty: 'beginner',
  },
  {
    name: 'Bulgarian Split Squat',
    primaryMuscle: 'Quadriceps',
    secondaryMuscles: ['Glutes', 'Hamstrings'],
    equipment: 'Dumbbell',
    instructions: 'Rear foot elevated, drop straight down, drive through the front heel.',
    formCues: ['Front shin near vertical', 'Torso slightly forward', 'Controlled tempo'],
    videoUrl: 'https://www.youtube.com/watch?v=2C-uNgKwPLE',
    difficulty: 'intermediate',
  },
  {
    name: 'Leg Extension',
    primaryMuscle: 'Quadriceps',
    secondaryMuscles: [],
    equipment: 'Machine',
    instructions: 'Extend knees to lockout against the pad, squeeze, lower under control.',
    formCues: ['Pause at top', 'No bouncing', 'Full range'],
    videoUrl: 'https://www.youtube.com/watch?v=YyvSfVjQeL0',
    difficulty: 'beginner',
  },
  {
    name: 'Lying Leg Curl',
    primaryMuscle: 'Hamstrings',
    secondaryMuscles: ['Calves'],
    equipment: 'Machine',
    instructions: 'Curl the pad toward your glutes, squeeze hamstrings, lower slowly.',
    formCues: ['Hips on pad', 'No jerking', 'Full contraction'],
    videoUrl: 'https://www.youtube.com/watch?v=1Tq3QdYUuHs',
    difficulty: 'beginner',
  },
  {
    name: 'Seated Leg Curl',
    primaryMuscle: 'Hamstrings',
    secondaryMuscles: ['Calves'],
    equipment: 'Machine',
    instructions: 'Curl the pad down and under, pause, control the return.',
    formCues: ['Back against pad', 'Pause at bottom', 'Slow eccentric'],
    videoUrl: 'https://www.youtube.com/watch?v=Orxowest56U',
    difficulty: 'beginner',
  },
  {
    name: 'Standing Calf Raise',
    primaryMuscle: 'Calves',
    secondaryMuscles: [],
    equipment: 'Machine',
    instructions: 'Rise onto the balls of your feet, pause at the top, lower for a deep stretch.',
    formCues: ['Full stretch at bottom', 'Pause at top', 'No bouncing'],
    videoUrl: 'https://www.youtube.com/watch?v=-M4-G8p8fmc',
    difficulty: 'beginner',
  },
  {
    name: 'Seated Calf Raise',
    primaryMuscle: 'Calves',
    secondaryMuscles: [],
    equipment: 'Machine',
    instructions: 'Knees under the pad, raise heels, squeeze, lower under control.',
    formCues: ['Deep stretch', 'Slow tempo', 'Full range'],
    videoUrl: 'https://www.youtube.com/watch?v=JbyjNymZOt0',
    difficulty: 'beginner',
  },
  {
    name: 'Glute Bridge',
    primaryMuscle: 'Glutes',
    secondaryMuscles: ['Hamstrings', 'Core'],
    equipment: 'Bodyweight',
    instructions: 'Lie on back, feet flat, drive hips up to a straight line, squeeze glutes.',
    formCues: ['Ribs down', 'Squeeze at top', 'Heels down'],
    videoUrl: 'https://www.youtube.com/watch?v=wPM8icPu6H8',
    difficulty: 'beginner',
  },
  {
    name: 'Cable Pull-Through',
    primaryMuscle: 'Glutes',
    secondaryMuscles: ['Hamstrings', 'Erectors'],
    equipment: 'Cable',
    instructions: 'Face away from a low pulley, hinge at the hips, snap hips forward to lockout.',
    formCues: ['Hinge not squat', 'Neutral spine', 'Squeeze glutes'],
    videoUrl: 'https://www.youtube.com/watch?v=Js-y2_QcJiU',
    difficulty: 'beginner',
  },
  {
    name: 'Sumo Deadlift',
    primaryMuscle: 'Glutes',
    secondaryMuscles: ['Hamstrings', 'Quadriceps', 'Erectors'],
    equipment: 'Barbell',
    instructions: 'Wide stance, grip inside knees, push the floor away, lock out hips.',
    formCues: ['Knees out', 'Chest up', 'Bar close'],
    videoUrl: 'https://www.youtube.com/watch?v=3Yr-pSGfQ8Q',
    difficulty: 'intermediate',
  },
  {
    name: 'Incline Barbell Bench Press',
    primaryMuscle: 'Upper Chest',
    secondaryMuscles: ['Front Delts', 'Triceps'],
    equipment: 'Barbell',
    instructions: 'Bench at ~30°, lower to upper chest, press up and slightly back.',
    formCues: ['Retract scapula', 'Elbows tucked', 'Controlled descent'],
    videoUrl: 'https://www.youtube.com/watch?v=SrqOu55lrYU',
    difficulty: 'intermediate',
  },
  {
    name: 'Dumbbell Bench Press',
    primaryMuscle: 'Chest',
    secondaryMuscles: ['Triceps', 'Front Delts'],
    equipment: 'Dumbbell',
    instructions: 'Press dumbbells from chest level up and together, lower for a deep stretch.',
    formCues: ['Wrists stacked', 'Control the stretch', 'Drive feet'],
    videoUrl: 'https://www.youtube.com/watch?v=VmB1G1K7v94',
    difficulty: 'beginner',
  },
  {
    name: 'Cable Chest Fly',
    primaryMuscle: 'Chest',
    secondaryMuscles: ['Front Delts'],
    equipment: 'Cable',
    instructions: 'From high or mid pulleys, sweep arms together in a hugging arc, squeeze.',
    formCues: ['Soft elbows', 'Lead with hands', 'Slow eccentric'],
    videoUrl: 'https://www.youtube.com/watch?v=Iwe6AmxVf7o',
    difficulty: 'beginner',
  },
  {
    name: 'Push-Up',
    primaryMuscle: 'Chest',
    secondaryMuscles: ['Triceps', 'Front Delts', 'Core'],
    equipment: 'Bodyweight',
    instructions: 'Body in a straight line, lower chest to the floor, press back up.',
    formCues: ['Elbows ~45°', 'Brace core', 'Full lockout'],
    videoUrl: 'https://www.youtube.com/watch?v=IODxDxX7oi4',
    difficulty: 'beginner',
  },
  {
    name: 'Chest Dip',
    primaryMuscle: 'Chest',
    secondaryMuscles: ['Triceps', 'Front Delts'],
    equipment: 'Bodyweight',
    instructions: 'Lean forward on parallel bars, lower until shoulders below elbows, press up.',
    formCues: ['Lean forward', 'Control the depth', "Don't flare hard"],
    videoUrl: 'https://www.youtube.com/watch?v=2z8JmcrW-As',
    difficulty: 'intermediate',
  },
  {
    name: 'Pec Deck Machine',
    primaryMuscle: 'Chest',
    secondaryMuscles: ['Front Delts'],
    equipment: 'Machine',
    instructions: 'Press the pads together in front of the chest, squeeze, return slowly.',
    formCues: ['Back on pad', 'Squeeze at center', 'No jerking'],
    videoUrl: 'https://www.youtube.com/watch?v=Z57CtFmRMxA',
    difficulty: 'beginner',
  },
  {
    name: 'Chin-Up',
    primaryMuscle: 'Lats',
    secondaryMuscles: ['Biceps', 'Upper Back'],
    equipment: 'Bodyweight',
    instructions: 'Underhand grip, pull chin over the bar, control the descent.',
    formCues: ['Depress scapula', 'Drive elbows down', 'Full hang at bottom'],
    videoUrl: 'https://www.youtube.com/watch?v=brhRXlOhsAM',
    difficulty: 'intermediate',
  },
  {
    name: 'Dumbbell Row',
    primaryMuscle: 'Lats',
    secondaryMuscles: ['Upper Back', 'Biceps'],
    equipment: 'Dumbbell',
    instructions: 'One hand on bench, row the dumbbell to the hip, squeeze, lower slowly.',
    formCues: ['Flat back', 'Row to hip', 'No torso twist'],
    videoUrl: 'https://www.youtube.com/watch?v=pYcpY20QaE8',
    difficulty: 'beginner',
  },
  {
    name: 'T-Bar Row',
    primaryMuscle: 'Upper Back',
    secondaryMuscles: ['Lats', 'Biceps', 'Erectors'],
    equipment: 'Machine',
    instructions: 'Hinge over the landmine, row the handle to the chest, squeeze the back.',
    formCues: ['Flat back', 'Pull to sternum', 'Controlled lower'],
    videoUrl: 'https://www.youtube.com/watch?v=j3Igk5nyZE4',
    difficulty: 'intermediate',
  },
  {
    name: 'Straight-Arm Pulldown',
    primaryMuscle: 'Lats',
    secondaryMuscles: ['Core'],
    equipment: 'Cable',
    instructions: 'Arms long, pull the bar down to the thighs in an arc, squeeze the lats.',
    formCues: ['Soft elbows', 'Lats drive it', 'Slow return'],
    videoUrl: 'https://www.youtube.com/watch?v=G9uNaXGTJ4w',
    difficulty: 'beginner',
  },
  {
    name: 'Back Extension',
    primaryMuscle: 'Erectors',
    secondaryMuscles: ['Glutes', 'Hamstrings'],
    equipment: 'Bodyweight',
    instructions: 'On a hyperextension bench, hinge down then raise to a straight line.',
    formCues: ['Neutral spine', 'Squeeze glutes', "Don't overextend"],
    videoUrl: 'https://www.youtube.com/watch?v=ph3pddpKzzw',
    difficulty: 'beginner',
  },
  {
    name: 'Dumbbell Shoulder Press',
    primaryMuscle: 'Shoulders',
    secondaryMuscles: ['Triceps', 'Upper Chest'],
    equipment: 'Dumbbell',
    instructions: 'Press dumbbells overhead from shoulder height, lower under control.',
    formCues: ['Ribs down', 'Wrists stacked', 'Full lockout'],
    videoUrl: 'https://www.youtube.com/watch?v=qEwKCR5JCog',
    difficulty: 'beginner',
  },
  {
    name: 'Arnold Press',
    primaryMuscle: 'Shoulders',
    secondaryMuscles: ['Triceps', 'Upper Chest'],
    equipment: 'Dumbbell',
    instructions: 'Start palms-in at chest, rotate out as you press overhead, reverse down.',
    formCues: ['Smooth rotation', 'Brace core', 'Controlled tempo'],
    videoUrl: 'https://www.youtube.com/watch?v=6Z15_WdXmVw',
    difficulty: 'intermediate',
  },
  {
    name: 'Cable Lateral Raise',
    primaryMuscle: 'Side Delts',
    secondaryMuscles: [],
    equipment: 'Cable',
    instructions: 'From a low pulley, raise the handle out to shoulder height, lower slowly.',
    formCues: ['Lead with elbow', 'No swing', 'Constant tension'],
    videoUrl: 'https://www.youtube.com/watch?v=PPrzBWZDOhA',
    difficulty: 'beginner',
  },
  {
    name: 'Reverse Pec Deck',
    primaryMuscle: 'Rear Delts',
    secondaryMuscles: ['Upper Back'],
    equipment: 'Machine',
    instructions: 'Facing the pad, sweep the handles back in an arc, squeeze rear delts.',
    formCues: ['Soft elbows', 'Squeeze the back', 'Slow return'],
    videoUrl: 'https://www.youtube.com/watch?v=6yMdhi2DVao',
    difficulty: 'beginner',
  },
  {
    name: 'Dumbbell Rear Delt Fly',
    primaryMuscle: 'Rear Delts',
    secondaryMuscles: ['Upper Back'],
    equipment: 'Dumbbell',
    instructions: 'Hinge forward, raise dumbbells out to the sides, squeeze, lower slowly.',
    formCues: ['Flat back', 'Lead with elbows', 'No momentum'],
    videoUrl: 'https://www.youtube.com/watch?v=EA7u4Q_8HQ0',
    difficulty: 'beginner',
  },
  {
    name: 'Barbell Shrug',
    primaryMuscle: 'Traps',
    secondaryMuscles: ['Forearms'],
    equipment: 'Barbell',
    instructions: 'Hold the bar at arms length, shrug shoulders straight up, pause, lower.',
    formCues: ['Straight up', 'Pause at top', 'No rolling'],
    videoUrl: 'https://www.youtube.com/watch?v=cJRVVxmytaM',
    difficulty: 'beginner',
  },
  {
    name: 'Dumbbell Bicep Curl',
    primaryMuscle: 'Biceps',
    secondaryMuscles: ['Forearms'],
    equipment: 'Dumbbell',
    instructions: 'Curl the dumbbells with elbows fixed, squeeze, lower under control.',
    formCues: ['Elbows pinned', 'No swing', 'Full extension'],
    videoUrl: 'https://www.youtube.com/watch?v=ykJmrZ5v0Oo',
    difficulty: 'beginner',
  },
  {
    name: 'Hammer Curl',
    primaryMuscle: 'Biceps',
    secondaryMuscles: ['Forearms'],
    equipment: 'Dumbbell',
    instructions: 'Neutral grip, curl the dumbbells, squeeze the brachialis, lower slowly.',
    formCues: ['Thumbs up', 'Elbows fixed', 'Controlled tempo'],
    videoUrl: 'https://www.youtube.com/watch?v=zC3nLlEvin4',
    difficulty: 'beginner',
  },
  {
    name: 'Preacher Curl',
    primaryMuscle: 'Biceps',
    secondaryMuscles: ['Forearms'],
    equipment: 'Machine',
    instructions: 'Arms on the pad, curl to peak contraction, lower to a near-full stretch.',
    formCues: ['Armpits on pad', 'No bouncing', "Don't fully drop"],
    videoUrl: 'https://www.youtube.com/watch?v=fIWP-FRFNU0',
    difficulty: 'beginner',
  },
  {
    name: 'Cable Bicep Curl',
    primaryMuscle: 'Biceps',
    secondaryMuscles: ['Forearms'],
    equipment: 'Cable',
    instructions: 'From a low pulley, curl the bar with elbows fixed, squeeze, lower slowly.',
    formCues: ['Constant tension', 'Elbows still', 'Slow eccentric'],
    videoUrl: 'https://www.youtube.com/watch?v=NFzTWp2qpiE',
    difficulty: 'beginner',
  },
  {
    name: 'Close-Grip Bench Press',
    primaryMuscle: 'Triceps',
    secondaryMuscles: ['Chest', 'Front Delts'],
    equipment: 'Barbell',
    instructions: 'Shoulder-width grip, lower to lower chest with tucked elbows, press up.',
    formCues: ['Elbows tucked', 'Wrists stacked', 'Full lockout'],
    videoUrl: 'https://www.youtube.com/watch?v=nEF0bv2FW94',
    difficulty: 'intermediate',
  },
  {
    name: 'Overhead Triceps Extension',
    primaryMuscle: 'Triceps',
    secondaryMuscles: [],
    equipment: 'Dumbbell',
    instructions: 'Hold a dumbbell overhead, lower behind the head, extend to lockout.',
    formCues: ['Elbows in', 'Deep stretch', 'Full lockout'],
    videoUrl: 'https://www.youtube.com/watch?v=YbX7Wd8jQ-Q',
    difficulty: 'beginner',
  },
  {
    name: 'Skull Crusher',
    primaryMuscle: 'Triceps',
    secondaryMuscles: [],
    equipment: 'Barbell',
    instructions: 'Lying down, lower the bar to the forehead with fixed elbows, extend up.',
    formCues: ['Elbows still', 'Slow lower', "Don't flare"],
    videoUrl: 'https://www.youtube.com/watch?v=d_KZxkY_0cM',
    difficulty: 'intermediate',
  },
  {
    name: 'Triceps Dip (Bench)',
    primaryMuscle: 'Triceps',
    secondaryMuscles: ['Front Delts', 'Chest'],
    equipment: 'Bodyweight',
    instructions: 'Hands on a bench behind you, lower the hips, press back to lockout.',
    formCues: ['Elbows back', 'Shoulders down', 'Controlled depth'],
    videoUrl: 'https://www.youtube.com/watch?v=6kALZikXxLc',
    difficulty: 'beginner',
  },
  {
    name: 'Hanging Leg Raise',
    primaryMuscle: 'Core',
    secondaryMuscles: ['Hip Flexors', 'Forearms'],
    equipment: 'Bodyweight',
    instructions: 'Hang from a bar, raise legs to hip height or higher, lower with control.',
    formCues: ['No swinging', 'Posterior tilt', 'Slow eccentric'],
    videoUrl: 'https://www.youtube.com/watch?v=Pr1ieGZ5atk',
    difficulty: 'intermediate',
  },
  {
    name: 'Cable Crunch',
    primaryMuscle: 'Core',
    secondaryMuscles: [],
    equipment: 'Cable',
    instructions: 'Kneel under a rope, crunch the ribs toward the pelvis, control back up.',
    formCues: ['Round the spine', 'Hips fixed', 'Squeeze abs'],
    videoUrl: 'https://www.youtube.com/watch?v=2fbujd2P9C0',
    difficulty: 'beginner',
  },
  {
    name: 'Russian Twist',
    primaryMuscle: 'Core',
    secondaryMuscles: ['Obliques'],
    equipment: 'Bodyweight',
    instructions: 'Seated, lean back slightly, rotate the torso side to side under control.',
    formCues: ['Chest tall', 'Rotate from the trunk', 'Controlled tempo'],
    videoUrl: 'https://www.youtube.com/watch?v=wkD8rjkodUI',
    difficulty: 'beginner',
  },
  {
    name: 'Side Plank',
    primaryMuscle: 'Obliques',
    secondaryMuscles: ['Core', 'Shoulders'],
    equipment: 'Bodyweight',
    instructions: 'On one forearm, stack the hips, lift into a straight line and hold.',
    formCues: ['Hips up', 'Stack shoulders', 'Brace hard'],
    videoUrl: 'https://www.youtube.com/watch?v=K2VljzCC16g',
    difficulty: 'beginner',
  },
  {
    name: 'Mountain Climber',
    primaryMuscle: 'Core',
    secondaryMuscles: ['Shoulders', 'Hip Flexors'],
    equipment: 'Bodyweight',
    instructions: 'In a plank, drive the knees toward the chest one at a time at pace.',
    formCues: ['Flat back', 'Hips low', 'Steady rhythm'],
    videoUrl: 'https://www.youtube.com/watch?v=nmwgirgXLYM',
    difficulty: 'beginner',
  },
  {
    name: 'Kettlebell Swing',
    primaryMuscle: 'Glutes',
    secondaryMuscles: ['Hamstrings', 'Core', 'Erectors'],
    equipment: 'Kettlebell',
    instructions: 'Hinge and hike the bell back, snap the hips to float it to chest height.',
    formCues: ['Hinge not squat', 'Snap the hips', 'Flat back'],
    videoUrl: 'https://www.youtube.com/watch?v=YSxHifyI6s8',
    difficulty: 'intermediate',
  },
  {
    name: 'Box Jump',
    primaryMuscle: 'Quadriceps',
    secondaryMuscles: ['Glutes', 'Calves'],
    equipment: 'Bodyweight',
    instructions: 'Dip and explode onto a box, land softly with bent knees, step down.',
    formCues: ['Soft landing', 'Full hip extension', 'Step down to reset'],
    videoUrl: 'https://www.youtube.com/watch?v=52r_Ul5k03g',
    difficulty: 'intermediate',
  },
  {
    name: 'Hip Abduction Machine',
    primaryMuscle: 'Glutes',
    secondaryMuscles: [],
    equipment: 'Machine',
    instructions: 'Push the pads outward with the knees, squeeze the glutes, return slowly.',
    formCues: ['Slight forward lean', 'Squeeze at end range', 'Controlled return'],
    videoUrl: 'https://www.youtube.com/watch?v=GoMzLO4N6r0',
    difficulty: 'beginner',
  },
  {
    name: 'Step-Up',
    primaryMuscle: 'Quadriceps',
    secondaryMuscles: ['Glutes', 'Hamstrings'],
    equipment: 'Dumbbell',
    instructions: 'Step onto a box driving through the lead heel, stand tall, lower slowly.',
    formCues: ['Drive through heel', 'No push-off from back foot', 'Controlled descent'],
    videoUrl: 'https://www.youtube.com/watch?v=dQqApCGd5Ss',
    difficulty: 'beginner',
  },
  {
    name: 'Hack Squat',
    primaryMuscle: 'Quadriceps',
    secondaryMuscles: ['Glutes'],
    equipment: 'Machine',
    instructions: 'Shoulders under the pads, descend to ~90°, drive up through mid-foot.',
    formCues: ['Back flat on pad', 'Knees track toes', 'Controlled depth'],
    videoUrl: 'https://www.youtube.com/watch?v=0tn5K9NlCfo',
    difficulty: 'beginner',
  },
  {
    name: 'Pendlay Row',
    primaryMuscle: 'Upper Back',
    secondaryMuscles: ['Lats', 'Biceps', 'Erectors'],
    equipment: 'Barbell',
    instructions: 'From a dead stop on the floor, explosively row to the lower chest each rep.',
    formCues: ['Torso parallel', 'Reset each rep', 'Flat back'],
    videoUrl: 'https://www.youtube.com/watch?v=ZlRrIsoDpKg',
    difficulty: 'advanced',
  },
  {
    name: 'Incline Dumbbell Curl',
    primaryMuscle: 'Biceps',
    secondaryMuscles: ['Forearms'],
    equipment: 'Dumbbell',
    instructions: 'Seated on an incline bench, curl with arms hanging back for a deep stretch.',
    formCues: ['Arms stay back', 'No swing', 'Full stretch'],
    videoUrl: 'https://www.youtube.com/watch?v=soxrZlIl35U',
    difficulty: 'beginner',
  },
  {
    name: 'Farmer\'s Carry',
    primaryMuscle: 'Forearms',
    secondaryMuscles: ['Traps', 'Core', 'Glutes'],
    equipment: 'Dumbbell',
    instructions: 'Hold heavy dumbbells at your sides and walk tall under control.',
    formCues: ['Shoulders back', 'Brace core', 'Steady steps'],
    videoUrl: 'https://www.youtube.com/watch?v=Fkzk_RqlYig',
    difficulty: 'beginner',
  },
];
