// IFCT-style Indian food composition seed (spec §12). per100g macros ground the
// LLM's photo/text estimates (spec §7.3). dishKey must match the lowercase
// canonical key the food prompts ask the model to emit. typicalServingG is the
// usual katori/piece weight, used as a portion fallback.

export interface SeedFood {
  name: string;
  dishKey: string;
  per100g: { calories: number; proteinG: number; carbsG: number; fatG: number };
  typicalServingG: number;
}

export const IFCT_FOODS: SeedFood[] = [
  { name: 'Dal (cooked toor/arhar)', dishKey: 'dal', per100g: { calories: 116, proteinG: 6.4, carbsG: 16, fatG: 2.7 }, typicalServingG: 150 },
  { name: 'Rajma (kidney bean curry)', dishKey: 'rajma', per100g: { calories: 140, proteinG: 7.2, carbsG: 18, fatG: 4.1 }, typicalServingG: 180 },
  { name: 'Chana masala', dishKey: 'chana masala', per100g: { calories: 164, proteinG: 7.5, carbsG: 20, fatG: 6.0 }, typicalServingG: 180 },
  { name: 'Paneer butter masala', dishKey: 'paneer butter masala', per100g: { calories: 230, proteinG: 9.0, carbsG: 9, fatG: 18 }, typicalServingG: 180 },
  { name: 'Palak paneer', dishKey: 'palak paneer', per100g: { calories: 180, proteinG: 8.5, carbsG: 7, fatG: 13 }, typicalServingG: 180 },
  { name: 'Paneer tikka', dishKey: 'paneer tikka', per100g: { calories: 270, proteinG: 18, carbsG: 6, fatG: 19 }, typicalServingG: 120 },
  { name: 'Soya chunk curry', dishKey: 'soya curry', per100g: { calories: 170, proteinG: 14, carbsG: 12, fatG: 7 }, typicalServingG: 180 },
  { name: 'Tofu stir fry', dishKey: 'tofu', per100g: { calories: 144, proteinG: 12, carbsG: 4, fatG: 9 }, typicalServingG: 150 },
  { name: 'Mixed vegetable sabzi', dishKey: 'sabzi', per100g: { calories: 120, proteinG: 3.0, carbsG: 12, fatG: 7 }, typicalServingG: 150 },
  { name: 'Aloo gobi', dishKey: 'aloo gobi', per100g: { calories: 130, proteinG: 3.2, carbsG: 15, fatG: 7 }, typicalServingG: 150 },
  { name: 'Bhindi masala', dishKey: 'bhindi', per100g: { calories: 125, proteinG: 2.5, carbsG: 11, fatG: 8 }, typicalServingG: 150 },
  { name: 'Plain roti (chapati)', dishKey: 'roti', per100g: { calories: 297, proteinG: 9.0, carbsG: 56, fatG: 4.5 }, typicalServingG: 40 },
  { name: 'Tandoori roti', dishKey: 'tandoori roti', per100g: { calories: 285, proteinG: 8.5, carbsG: 55, fatG: 4.0 }, typicalServingG: 50 },
  { name: 'Plain paratha', dishKey: 'paratha', per100g: { calories: 330, proteinG: 7.0, carbsG: 45, fatG: 13 }, typicalServingG: 60 },
  { name: 'Steamed white rice', dishKey: 'rice', per100g: { calories: 130, proteinG: 2.7, carbsG: 28, fatG: 0.3 }, typicalServingG: 150 },
  { name: 'Jeera rice', dishKey: 'jeera rice', per100g: { calories: 170, proteinG: 3.0, carbsG: 30, fatG: 4.0 }, typicalServingG: 150 },
  { name: 'Vegetable biryani', dishKey: 'veg biryani', per100g: { calories: 165, proteinG: 4.0, carbsG: 27, fatG: 4.5 }, typicalServingG: 200 },
  { name: 'Plain dosa', dishKey: 'dosa', per100g: { calories: 168, proteinG: 3.9, carbsG: 30, fatG: 3.7 }, typicalServingG: 90 },
  { name: 'Masala dosa', dishKey: 'masala dosa', per100g: { calories: 190, proteinG: 4.2, carbsG: 30, fatG: 6.5 }, typicalServingG: 150 },
  { name: 'Idli', dishKey: 'idli', per100g: { calories: 130, proteinG: 4.0, carbsG: 26, fatG: 0.8 }, typicalServingG: 40 },
  { name: 'Sambar', dishKey: 'sambar', per100g: { calories: 85, proteinG: 3.5, carbsG: 12, fatG: 2.5 }, typicalServingG: 150 },
  { name: 'Curd / dahi (plain)', dishKey: 'curd', per100g: { calories: 60, proteinG: 3.1, carbsG: 4.7, fatG: 3.3 }, typicalServingG: 100 },
  { name: 'Raita', dishKey: 'raita', per100g: { calories: 70, proteinG: 2.8, carbsG: 5, fatG: 4 }, typicalServingG: 100 },
  { name: 'Poha', dishKey: 'poha', per100g: { calories: 150, proteinG: 2.6, carbsG: 27, fatG: 3.5 }, typicalServingG: 150 },
  { name: 'Upma', dishKey: 'upma', per100g: { calories: 160, proteinG: 3.5, carbsG: 25, fatG: 5.0 }, typicalServingG: 150 },
  { name: 'Boiled egg', dishKey: 'boiled egg', per100g: { calories: 155, proteinG: 13, carbsG: 1.1, fatG: 11 }, typicalServingG: 50 },
  { name: 'Egg curry', dishKey: 'egg curry', per100g: { calories: 165, proteinG: 9, carbsG: 6, fatG: 12 }, typicalServingG: 180 },
  { name: 'Chicken curry', dishKey: 'chicken curry', per100g: { calories: 180, proteinG: 16, carbsG: 5, fatG: 11 }, typicalServingG: 180 },
  { name: 'Dal makhani', dishKey: 'dal makhani', per100g: { calories: 165, proteinG: 6.0, carbsG: 14, fatG: 9.5 }, typicalServingG: 180 },
  { name: 'Moong dal (cooked)', dishKey: 'moong dal', per100g: { calories: 105, proteinG: 7.0, carbsG: 15, fatG: 1.8 }, typicalServingG: 150 },
  { name: 'Masoor dal (cooked)', dishKey: 'masoor dal', per100g: { calories: 116, proteinG: 7.5, carbsG: 17, fatG: 1.5 }, typicalServingG: 150 },
  { name: 'Chana dal (cooked)', dishKey: 'chana dal', per100g: { calories: 130, proteinG: 7.8, carbsG: 18, fatG: 2.8 }, typicalServingG: 150 },
  { name: 'Kadhi (besan-yogurt curry)', dishKey: 'kadhi', per100g: { calories: 110, proteinG: 3.5, carbsG: 9, fatG: 6.5 }, typicalServingG: 180 },
  { name: 'Chole (chickpea curry)', dishKey: 'chole', per100g: { calories: 170, proteinG: 7.8, carbsG: 22, fatG: 6.0 }, typicalServingG: 180 },
  { name: 'Kala chana (black chickpeas)', dishKey: 'kala chana', per100g: { calories: 155, proteinG: 8.5, carbsG: 24, fatG: 2.8 }, typicalServingG: 150 },
  { name: 'Paneer bhurji', dishKey: 'paneer bhurji', per100g: { calories: 250, proteinG: 16, carbsG: 6, fatG: 18 }, typicalServingG: 120 },
  { name: 'Shahi paneer', dishKey: 'shahi paneer', per100g: { calories: 245, proteinG: 9.5, carbsG: 10, fatG: 19 }, typicalServingG: 180 },
  { name: 'Matar paneer', dishKey: 'matar paneer', per100g: { calories: 190, proteinG: 9.0, carbsG: 11, fatG: 12 }, typicalServingG: 180 },
  { name: 'Raw paneer (cubes)', dishKey: 'paneer', per100g: { calories: 265, proteinG: 18, carbsG: 3.6, fatG: 20 }, typicalServingG: 50 },
  { name: 'Soya chunks (dry)', dishKey: 'soya chunks', per100g: { calories: 345, proteinG: 52, carbsG: 33, fatG: 0.5 }, typicalServingG: 40 },
  { name: 'Baingan bharta', dishKey: 'baingan bharta', per100g: { calories: 110, proteinG: 2.0, carbsG: 9, fatG: 7.5 }, typicalServingG: 150 },
  { name: 'Aloo matar', dishKey: 'aloo matar', per100g: { calories: 120, proteinG: 3.5, carbsG: 16, fatG: 5.0 }, typicalServingG: 150 },
  { name: 'Aloo jeera', dishKey: 'aloo jeera', per100g: { calories: 140, proteinG: 2.5, carbsG: 20, fatG: 6.0 }, typicalServingG: 150 },
  { name: 'Palak (sauteed spinach)', dishKey: 'palak', per100g: { calories: 70, proteinG: 3.0, carbsG: 5, fatG: 4.0 }, typicalServingG: 150 },
  { name: 'Methi (fenugreek sabzi)', dishKey: 'methi sabzi', per100g: { calories: 95, proteinG: 4.0, carbsG: 7, fatG: 5.5 }, typicalServingG: 150 },
  { name: 'Mixed veg korma', dishKey: 'veg korma', per100g: { calories: 175, proteinG: 4.0, carbsG: 12, fatG: 12 }, typicalServingG: 180 },
  { name: 'Whole wheat bread (slice)', dishKey: 'whole wheat bread', per100g: { calories: 250, proteinG: 9.0, carbsG: 45, fatG: 3.5 }, typicalServingG: 30 },
  { name: 'Naan', dishKey: 'naan', per100g: { calories: 310, proteinG: 8.5, carbsG: 52, fatG: 7.5 }, typicalServingG: 90 },
  { name: 'Aloo paratha', dishKey: 'aloo paratha', per100g: { calories: 260, proteinG: 6.0, carbsG: 38, fatG: 9.5 }, typicalServingG: 120 },
  { name: 'Puri (fried bread)', dishKey: 'puri', per100g: { calories: 360, proteinG: 7.0, carbsG: 45, fatG: 17 }, typicalServingG: 30 },
  { name: 'Brown rice (cooked)', dishKey: 'brown rice', per100g: { calories: 123, proteinG: 2.7, carbsG: 26, fatG: 1.0 }, typicalServingG: 150 },
  { name: 'Curd rice', dishKey: 'curd rice', per100g: { calories: 130, proteinG: 3.5, carbsG: 20, fatG: 3.5 }, typicalServingG: 200 },
  { name: 'Khichdi', dishKey: 'khichdi', per100g: { calories: 120, proteinG: 4.5, carbsG: 20, fatG: 2.5 }, typicalServingG: 200 },
  { name: 'Chicken biryani', dishKey: 'chicken biryani', per100g: { calories: 190, proteinG: 9.0, carbsG: 24, fatG: 7.0 }, typicalServingG: 250 },
  { name: 'Rava (semolina) idli', dishKey: 'rava idli', per100g: { calories: 145, proteinG: 4.0, carbsG: 25, fatG: 3.0 }, typicalServingG: 45 },
  { name: 'Medu vada', dishKey: 'medu vada', per100g: { calories: 245, proteinG: 7.0, carbsG: 28, fatG: 12 }, typicalServingG: 50 },
  { name: 'Uttapam', dishKey: 'uttapam', per100g: { calories: 165, proteinG: 4.5, carbsG: 27, fatG: 4.5 }, typicalServingG: 120 },
  { name: 'Pongal', dishKey: 'pongal', per100g: { calories: 150, proteinG: 4.0, carbsG: 22, fatG: 5.0 }, typicalServingG: 180 },
  { name: 'Coconut chutney', dishKey: 'coconut chutney', per100g: { calories: 200, proteinG: 3.0, carbsG: 7, fatG: 18 }, typicalServingG: 40 },
  { name: 'Samosa', dishKey: 'samosa', per100g: { calories: 300, proteinG: 5.0, carbsG: 32, fatG: 17 }, typicalServingG: 60 },
  { name: 'Pakora (mixed)', dishKey: 'pakora', per100g: { calories: 315, proteinG: 6.5, carbsG: 28, fatG: 19 }, typicalServingG: 60 },
  { name: 'Dhokla', dishKey: 'dhokla', per100g: { calories: 160, proteinG: 6.0, carbsG: 24, fatG: 4.0 }, typicalServingG: 80 },
  { name: 'Vada pav', dishKey: 'vada pav', per100g: { calories: 290, proteinG: 6.5, carbsG: 40, fatG: 11 }, typicalServingG: 130 },
  { name: 'Pav bhaji', dishKey: 'pav bhaji', per100g: { calories: 160, proteinG: 3.5, carbsG: 18, fatG: 8.0 }, typicalServingG: 250 },
  { name: 'Chana chaat', dishKey: 'chana chaat', per100g: { calories: 150, proteinG: 6.0, carbsG: 21, fatG: 4.5 }, typicalServingG: 150 },
  { name: 'Paneer roll', dishKey: 'paneer roll', per100g: { calories: 245, proteinG: 9.5, carbsG: 25, fatG: 12 }, typicalServingG: 150 },
  { name: 'Lassi (sweet)', dishKey: 'lassi', per100g: { calories: 95, proteinG: 2.8, carbsG: 14, fatG: 3.0 }, typicalServingG: 250 },
  { name: 'Buttermilk (chaas)', dishKey: 'buttermilk', per100g: { calories: 40, proteinG: 2.5, carbsG: 4.5, fatG: 1.5 }, typicalServingG: 200 },
  { name: 'Toned milk', dishKey: 'milk', per100g: { calories: 62, proteinG: 3.2, carbsG: 4.8, fatG: 3.3 }, typicalServingG: 200 },
  { name: 'Greek yogurt (plain)', dishKey: 'greek yogurt', per100g: { calories: 59, proteinG: 10, carbsG: 3.6, fatG: 0.4 }, typicalServingG: 150 },
  { name: 'Ghee', dishKey: 'ghee', per100g: { calories: 900, proteinG: 0, carbsG: 0, fatG: 100 }, typicalServingG: 10 },
  { name: 'Rolled oats (dry)', dishKey: 'oats', per100g: { calories: 389, proteinG: 13, carbsG: 66, fatG: 7.0 }, typicalServingG: 40 },
  { name: 'Scrambled eggs', dishKey: 'scrambled eggs', per100g: { calories: 165, proteinG: 11, carbsG: 1.6, fatG: 12 }, typicalServingG: 100 },
  { name: 'Egg omelette', dishKey: 'omelette', per100g: { calories: 155, proteinG: 11, carbsG: 1.5, fatG: 12 }, typicalServingG: 120 },
  { name: 'Grilled chicken breast', dishKey: 'chicken breast', per100g: { calories: 165, proteinG: 31, carbsG: 0, fatG: 3.6 }, typicalServingG: 150 },
  { name: 'Tandoori chicken', dishKey: 'tandoori chicken', per100g: { calories: 175, proteinG: 25, carbsG: 3, fatG: 7.0 }, typicalServingG: 150 },
  { name: 'Fish curry', dishKey: 'fish curry', per100g: { calories: 150, proteinG: 15, carbsG: 4, fatG: 8.5 }, typicalServingG: 180 },
  { name: 'Banana', dishKey: 'banana', per100g: { calories: 89, proteinG: 1.1, carbsG: 23, fatG: 0.3 }, typicalServingG: 120 },
  { name: 'Apple', dishKey: 'apple', per100g: { calories: 52, proteinG: 0.3, carbsG: 14, fatG: 0.2 }, typicalServingG: 150 },
  { name: 'Mango', dishKey: 'mango', per100g: { calories: 60, proteinG: 0.8, carbsG: 15, fatG: 0.4 }, typicalServingG: 150 },
  { name: 'Almonds', dishKey: 'almonds', per100g: { calories: 579, proteinG: 21, carbsG: 22, fatG: 50 }, typicalServingG: 28 },
  { name: 'Peanuts (roasted)', dishKey: 'peanuts', per100g: { calories: 567, proteinG: 26, carbsG: 16, fatG: 49 }, typicalServingG: 30 },
  { name: 'Peanut butter', dishKey: 'peanut butter', per100g: { calories: 588, proteinG: 25, carbsG: 20, fatG: 50 }, typicalServingG: 20 },
  { name: 'Whey protein (scoop)', dishKey: 'whey protein', per100g: { calories: 400, proteinG: 80, carbsG: 8, fatG: 6.0 }, typicalServingG: 30 },
  { name: 'Sprouts salad (moong)', dishKey: 'sprouts', per100g: { calories: 100, proteinG: 7.5, carbsG: 16, fatG: 0.6 }, typicalServingG: 100 },
  { name: 'Vegetable salad (plain)', dishKey: 'salad', per100g: { calories: 35, proteinG: 1.5, carbsG: 6, fatG: 0.4 }, typicalServingG: 150 },
];
