import { defineSecret, defineString } from 'firebase-functions/params';
import { fetchWithRetry } from './http';
import { LLMError } from './types';

// Lyzr agent integration (the plan engine). Workout + diet plans are generated by
// two separate Lyzr Studio agents — keys live in Secret Manager, never in the app.
// Food estimation (photo/label/text) stays on Gemini; Lyzr is plan-generation only.

export const LYZR_API_KEY = defineSecret('LYZR_API_KEY');
export const LYZR_WORKOUT_AGENT_ID = defineString('LYZR_WORKOUT_AGENT_ID', { default: '' });
export const LYZR_DIET_AGENT_ID = defineString('LYZR_DIET_AGENT_ID', { default: '' });
export const LYZR_BASE_URL = defineString('LYZR_BASE_URL', {
  default: 'https://agent-prod.studio.lyzr.ai/v3/inference/chat/',
});

/** Secrets bound on every function that calls a Lyzr agent. */
export const LYZR_SECRETS = [LYZR_API_KEY];

/**
 * Run a one-shot inference against a Lyzr agent and return its text response.
 *
 * A fresh session_id per call (agentId + uid + timestamp) means the agent treats
 * each generation as standalone — no carry-over of an earlier session's clarifying
 * questions (the agents have cross_session:false). The caller is responsible for
 * crafting `message` to force strict JSON; we just relay the raw text back.
 */
export async function runLyzrAgent(
  agentId: string,
  uid: string,
  message: string,
): Promise<string> {
  if (!agentId) {
    throw new LLMError('Lyzr agent id not configured', undefined, false);
  }
  const sessionId = `${agentId}-${uid}-${Date.now()}`;
  const res = await fetchWithRetry(
    LYZR_BASE_URL.value(),
    {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'x-api-key': LYZR_API_KEY.value(),
      },
      body: JSON.stringify({
        user_id: uid,
        agent_id: agentId,
        session_id: sessionId,
        message,
      }),
    },
    // Plan generation with Opus can be slow; give it more headroom than the 30s
    // default. Worst case must stay UNDER the calling function's timeoutSeconds
    // (see planCallOpts) — otherwise the function is force-killed mid-retry before
    // generateAndStore*'s catch can record a terminal status, stranding the user
    // on 'generating'. 90s × (1 + 1 retry) + backoff ≈ 181s < 240s function budget.
    { timeoutMs: 90_000, retries: 1 },
  );

  const json = (await res.json()) as {
    response?: string;
    message?: string;
    data?: string;
    error?: string | { message?: string };
  };

  if (json.error) {
    const msg = typeof json.error === 'string' ? json.error : json.error.message;
    throw new LLMError(`Lyzr error: ${msg ?? 'unknown'}`, res.status);
  }

  // Lyzr's chat inference returns the agent text on `response`; fall back across
  // a couple of plausible field names so a minor API shape change degrades to a
  // clear "no content" error rather than a cryptic parse failure downstream.
  const text = json.response ?? json.message ?? json.data;
  if (!text || !text.trim()) {
    throw new LLMError('Lyzr returned no content', res.status);
  }
  return text;
}
